### ISSUE TITLE
time.com not loading content

### ISSUE THREAD

**Issue by garvankeeley** [bbondy/abp-filter-parser-cpp#17]
This resource is getting block: see 2 urls below
The context domain is: http://www.time.com
The type of request is: set to FONoFilterOption
Expected: It doesn’t block the content on the page
Actual: It does block. If I whitelist s1.wp.com/_static then the site loads

```
https://s1.wp.com/_static/??-eJyVkEESwjAIRS9kxdqqK8ezZCqNZEjCFKr29qY3kA0L5r0P8+Ej3VSLYTGwF2ZUeJOAUcbzqR8hKTxJDaTyNhNzx3UKrFaXEPGY9AD/BvAaqahHWY2YbPMo+2IHZ4ouDbNwMHS9J2Exal24DsVvwx/53o+X4XYd2kw/w1iKoA==

https://s1.wp.com/_static/??-eJyV0NtOBCEMBuAXkql7UK+Mz1KHzk5JC0jBFZ/e3YneGLORm4aUfH/Twjm7OcVKsUJdScngnTNUVtrf744QDDxb3RrOL3kKdgcjxoQ92ZrOwxLzv6YJvxYsHTT5JpfPSijcFKqf3ff7d4w2l6WdOBrs3TUsbJkOI0qvPNuNuT9Q8LM7SeivOLw1Kn2yFLFMynF4V6GlFmQZhr5HVJ5XQk9lWK9JKeOJhuHCH3TrSn8rxe00L/q8Oz4cnh4Plxq+ALAt5+Y=
```

**Comment by bbondy** [comment]
Could you try with 1.1.5?
I think it's fixed with:
https://github.com/bbondy/abp-filter-parser-cpp/commit/864470b0fd94fe241cb4d78c274927a5c8bfe137

**Comment by garvankeeley** [comment]
fixed
