### ISSUE TITLE
Google search sponsored hit blocked

### ISSUE THREAD

**Issue by garvankeeley** [bbondy/abp-filter-parser-cpp#19]
After a google search, the sponsored top hit won't load (which appears as the first result sporadically in a google search, not sure of why this only shows sometimes). In this case searching for 'nytimes'
This resource getting blocked: see urls below
The context domain is: www.google.com
The type of request is: set to FONoFilterOption
Expected: It doesn’t block the page loading
Actual: page loading is blocked

```
https://www.google.com/aclk?sa=l&ai=CCnghNL-qVu78CoWUpAOn34ngD9O0gqQIi-CHz7EBu9Tsyf0BCAAQASCz-P4YYP2gmYHoA6AB1bu10wPIAQGqBCRP0OIa5qwwJWPYIATnb57z5N0U0vDU6Qr3HAOoB1EcoQK0FtvYBgSAB5PEyiyIBwGQBwKoB6a-G9gHAQ&sig=AOD64_3BeRm7DcIoCeQItqMFDSg_RosM7Q&clui=0&q=&ved=0ahUKEwj6taSg7s3KAhXGvYMKHXvsBRoQ0QwIGg&adurl=http://5195.xg4ken.com/trk/v1%3Fprof%3D521%26camp%3D138461%26affcode%3Dkw503631%26kct%3Dgoogle%26kchid%3D7667080588%26cid%3D47590031387%26networkType%3Dsearch%26kdv%3Dt%26criteriaid%3Dkwd-68069042747%26adgroupid%3D9857598707%26campaignid%3D179261027%26locphy%3D9000968%26adpos%3D1t1%26url%3Dhttp://p1673.ic-live.com/redirect%3FcID%3D1673%26campID%3D26%26cdid%3D5263%26ic_key%3Dnytimes%2520international%26ko_key_id%3D521_503631%26ic_eid%3D3%26ic_euid%3D_kenshoo_clickid_%26ic_mid%3D_kenshoo_clickid_%26ic_url%3Dhttp://international.nytimes.com/subscriptions/inyt/lp87JWF.html%3FcampaignId%3D87JWF
```

**Comment by bbondy** [comment]
Can you determine when it's a main document load?

**Comment by bbondy** [comment]
@garvankeeley last question was for you, just wondering if you can detect when a resource request is the main document being loaded. I'm wondering if we should just always let through main document loads. I can tell on the laptop side.

**Comment by garvankeeley** [comment]
sorry missed your earlier question. I had taken out that check because I had misunderstood that the lib was performing that check. It does work now

**Comment by bbondy** [comment]
So this works on iOS now?

**Comment by bbondy** [comment]
@SergeyZhukovsky please verify this works for you in Android.
Closing this since it works on laptop now.

**Comment by garvankeeley** [comment]
Works on iOS with the check added in 7bc8aa1

**Comment by SergeyZhukovsky** [comment]
It doesn't work on Android, will check Garvan's commit later today

**Comment by bbondy** [comment]
I fixed on laptop today as well.
@SergeyZhukovsky for your reference:
https://github.com/brave/browser-laptop/commit/994034d5abb44b1f008951397d34d43d65884461

**Comment by SergeyZhukovsky** [comment]
Fixed it here 
https://github.com/brave/browser-android/commit/f05e8018e4050f62a231e7d45a30dc7e6d73fa73
