### ISSUE TITLE
Performance profile: indexOf and getUrlHost are 45% load

### ISSUE THREAD

**Issue by garvankeeley** [bbondy/abp-filter-parser-cpp#2]
<img width="775" alt="screenshot 2015-11-02 12 42 55" src="https://cloud.githubusercontent.com/assets/5495083/10889819/39411cb2-8162-11e5-8a98-093aefe83c1f.png">

**Comment by garvankeeley** [comment]
Just FYI for now, not sure what can be done.

**Comment by bbondy** [comment]
hopefully the host anchored opt I'm doing will mostly get rid of this, will keep this around though

**Comment by garvankeeley** [comment]
Just to update, on the latest perf testing, this is 18% ± 2% of the load

**Comment by bbondy** [comment]
So if a page load is 3s you're seeing 1.5s in ABP code?
Metrics: currently seeing ~10% reduction in page load with blocking on. About ~15% of the run-time with blocking on is spent in the blocking code. 
This is time measured from request initiated to DOM "loaded" event.

**Comment by garvankeeley** [comment]
A page load is 3s -> 1.5s in ABP code, yes to that (according to the profile). That will only happen on first load of a page though, unless I disable my local caching. I can do more detailed profiling, especially if it doesn't correlate with expectations.

**Comment by bbondy** [comment]
there's still optimizations for ABP but 1.5s of 3s sounds wrong, I think something else is going on too.

**Comment by bbondy** [comment]
Let me know each set of URLs and I can time it here, I'd expect more like 35ms currently.

**Comment by garvankeeley** [comment]
I'll get you that info, but I wanted to quickly get a profile with the latest code. Here is the first 1 sec of loading imore.com. 700ms (70%) is spend in ABP code, all off main thread. [I have recently changed the webview threading, and am now seeing all the ABP code in the WTF thread (webkit thread, WTF is 'Web Template Framework']
The is a pessimistic view of course, most of the URLs are checked in the first second of the load. 
<img width="531" alt="screenshot 2015-11-04 10 53 22" src="https://cloud.githubusercontent.com/assets/5495083/10943441/69778048-82e2-11e5-8225-7a741291e0e8.png">

**Comment by bbondy** [comment]
Optimized here:
https://github.com/bbondy/abp-filter-parser-cpp/commit/c3e87304b2204b8526bd54f8baef2a25630fa995

<img width="726" alt="screenshot 2015-11-22 23 23 01" src="https://cloud.githubusercontent.com/assets/831718/11329888/03ff5c30-9170-11e5-9b44-408dfa43fc1b.png">

Could possibly be improved more but will do after profiling in new tasks.
