### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by luixxiul** [bbondy/abp-filter-parser-cpp#27]
On Lubuntu 15.10 with ``node -v 5.5.0`` and ``nodejs -v 5.11.0``, ``npm install`` fails.

````
make: Entering directory '/home/test/browser-laptop/node_modules/abp-filter-parser-cpp/build'
  CXX(target) Release/obj.target/abp-filter-parser-cpp/addon.o
In file included from ../ABPFilterParser.h:9:0,
                 from ../ABPFilterParserWrap.h:12,
                 from ../addon.cpp:7:
.././filter.h:12:25: fatal error: BloomFilter.h: : No such file or directory
compilation terminated.
abp-filter-parser-cpp.target.mk:102: recipe for target 'Release/obj.target/abp-filter-parser-cpp/addon.o' failed
make: *** [Release/obj.target/abp-filter-parser-cpp/addon.o] Error 1
````

It says BloomFilter.h is missing, and this error seems to block building Brave.

**Comment by luixxiul** [comment]
Same as https://github.com/brave/browser-laptop/issues/214

**Comment by bbondy** [comment]
The solution there should work, let us know if not.

**Comment by bbondy** [comment]
thanks @luixxiul

**Comment by luixxiul** [comment]
@bbondy, I set up a new virtual machine (Lubuntu 15.10) and 

````
git clone https://github.com/tj/n.git
sudo make install
sudo n 5.5.0

sudo npm install -g node-gyp@3.2.1
sudo apt-get install libgnome-keyring-dev
git clone https://github.com/brave/browser-laptop.git
cd browser-laptop
sudo npm i
````

still I get the same error. I'm not sure what is wrong at all :-(

**Comment by luixxiul** [comment]
@bbondy, I set up a new virtual machine (Lubuntu 15.10) and 

````
git clone https://github.com/tj/n.git
sudo make install
sudo n 5.5.0

sudo npm install -g node-gyp@3.2.1
sudo apt-get install libgnome-keyring-dev
git clone https://github.com/brave/browser-laptop.git
cd browser-laptop
sudo npm i
````

still I get the same error. I'm not sure what is wrong at all :-(
``npm i --unsafe-perms`` doesn't work either.

cc: @diracdeltas

**Comment by luixxiul** [comment]
Why don't you just include BloomFilter.h? You cannot find it in the master branch. Isn't it the cause of the error?

https://github.com/bbondy/abp-filter-parser-cpp/blob/0f4c8aadb5ad51ea1bef21f0d808b89df844f0f6/filter.h#L12

**Comment by luixxiul** [comment]
It has been reported at:
https://github.com/brave/browser-laptop/issues/214#issuecomment-176698618
https://github.com/brave/browser-laptop/issues/214#issuecomment-176993388

**Comment by luixxiul** [comment]
FWIW the solution that worked: https://gist.github.com/luixxiul/e294f2e5ef5bdf5ab6910d8224a9b7a9
