### ISSUE TITLE
Memory alloc review

### ISSUE THREAD

**Issue by garvankeeley** [bbondy/abp-filter-parser-cpp#7]
@bbondy if you don't mind, please double-check these are being cleaned up:
https://github.com/bbondy/abp-filter-parser-cpp/blob/master/filter.cpp#L163

https://github.com/bbondy/abp-filter-parser-cpp/blob/master/filter.cpp#L265
(and the line before)

**Comment by bbondy** [comment]
The 2nd one is a leak thanks for finding. The first one is not. I'll do an update a bit later today when I'm on OSX again.

**Comment by bbondy** [comment]
@garvankeeley should be fixed in abp-filter-parser-cpp@0.1.13, please update.
