### ISSUE TITLE
Remove implicit conversion warnings

### ISSUE THREAD

**Issue by garvankeeley** [bbondy/abp-filter-parser-cpp#9]
Seeing lots of these warnings:

<img width="850" alt="screenshot 2015-11-24 11 56 16" src="https://cloud.githubusercontent.com/assets/5495083/11374123/815bd77a-92a2-11e5-8b44-eb38160f3d1b.png">

**Comment by bbondy** [comment]
I think this is already fixed in the tip. Publish 0.2.9, if you see in that one or later please re-open.

**Comment by garvankeeley** [comment]
thanks, will try
